services:
  report-service:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: report-service
    ports:
      - "8802:8802"
    environment:
      - GO_ENV=production
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=vudangducminh
      - POSTGRES_PASSWORD=Amogus69420
      - POSTGRES_DB=postgres
    networks:
      - report_service_network
      - server_service_network
      - user_service_network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs  # Mount logs directory
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8802/api/v1/health || exit 1"]
      interval: 30s
  
networks:
  report_service_network:
    driver: bridge
  user_service_network:
    external: true
    name: config_user_service_network
  server_service_network:
    external: true
    name: config_server_service_network
