services:
  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=vudangducminh
      - POSTGRES_PASSWORD=Amogus69420
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sms_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vudangducminh -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - sms_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  user_service:
    build:
      context: ../service/user_service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8800:8800"
    environment:
      - GO_ENV=production
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=vudangducminh
      - POSTGRES_PASSWORD=Amogus69420
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - sms_network
    volumes:
      - ./service/user_service/logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8800/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  server_service:
    build:
      context: ../service/server_service
      dockerfile: Dockerfile
    container_name: server_service
    ports:
      - "8801:8801"
    environment:
      - GO_ENV=production
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=vudangducminh
      - POSTGRES_PASSWORD=Amogus69420
      - POSTGRES_DB=postgres
      - USER_SERVICE_URL=http://user_service:8800
    depends_on:
      user_service:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    networks:
      - sms_network
    volumes:
      - ./service/server_service/logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8801/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  report_service:
    build:
      context: ../service/report_service
      dockerfile: Dockerfile
    container_name: report_service
    ports:
      - "8802:8802"
    environment:
      - GO_ENV=production
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=vudangducminh
      - POSTGRES_PASSWORD=Amogus69420
      - POSTGRES_DB=postgres
      - USER_SERVICE_URL=http://user_service:8800
      - SERVER_SERVICE_URL=http://server_service:8801
    depends_on:
      user_service:
        condition: service_healthy
      server_service:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    networks:
      - sms_network
    volumes:
      - ./service/report_service/logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8802/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  healthcheck_service:
    build:
      context: ../service/healthcheck_service
      dockerfile: Dockerfile
    container_name: healthcheck_service
    ports:
      - "8803:8803"
    environment:
      - GO_ENV=production
      - USER_SERVICE_URL=http://user_service:8800
      - SERVER_SERVICE_URL=http://server_service:8801
      - REPORT_SERVICE_URL=http://report_service:8802
    depends_on:
      server_service:
        condition: service_healthy
    networks:
      - sms_network
    volumes:
      - ./service/healthcheck_service/logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8803/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  sms_network:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch_data: